# Generated by Django 4.1.7 on 2023-04-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.paymentrequest'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
