# Generated by Django 4.1.7 on 2023-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_currency',
            field=models.CharField(max_length=3),
        ),
    ]
